#!/bin/bash

function ppc { 
  local parseable=0
  if [ "$#" -eq "3" ]; then
    if [ "$3" == "--parseable" ];then
      parseable=1
      # set arglist to only the first two
      set -- "${@:1:2}"
    else
      echo 'unknown argument' >&2
      return 1
    fi
  fi
  if [ "$#" -ne "2" ]; then
    echo "Usage: $0 <-r,-w,-x> (path) [--parseable]" >&2
    return 1
  fi
  local fullPath=$2
  local i
  local pathChunk
  local builtPath
  local lastExistingPath
  local dirPath="$(dirname "$fullPath")"
   
  if [ -e "$fullPath" ];then
    if [ ! "$1" "$fullPath" ];then
      if [ "$parseable" -eq "0" ];then
        echo "'$fullPath' does not have permission $1" >&2
      else
        echo -n "$dirPath" >&2
      fi
      return 77
    else
      return 0
    fi
  fi

  if [ "$dirPath" == '.' ];then
    dirPath="$PWD"
  fi

  while IFS='/' read -ra DIR; do
    for i in "${DIR[@]}"; do
      pathChunk=$i
      if [ -z "$pathChunk" ]; then
        #absolute path
        continue
      fi
      builtPath="$builtPath"/"$pathChunk"
      if [ ! -x $builtPath ];then
        # path does not exist with -x permissions
        if [ "$parseable" -eq "0" ];then
          echo "path exists with -x permissions up to '$lastExistingPath'" >&2
        else
          echo -n "$lastExistingPath" >&2
        fi
        # do we lack permissions or simply not exist?
        if [ ! -e $builtPath ];then
            if [ "$parseable" -eq "0" ];then
              echo "==========| '$pathChunk' does not exist" >&2
            fi
            return 66
        else #file exists, so must be a permission error
          if [ "$parseable" -eq "0" ];then
            echo "==========| '$pathChunk' does not have permission -x" >&2
          fi
          return 77
        fi
      else
        lastExistingPath=$builtPath
      fi
    done
  done <<< "$fullPath"
}

function fpc {
  ppc -r "$@"
  return $?
}
